import { get, route } from 'remix/routes'

export const routes = route({
  assets: get('/assets/*path'),
  home: '/',
  store: '/store',
  school: '/school',
  cafe: '/cafe',
  market: '/market',
  storeAbout: '/store/about',
  storeWeb: '/store/web',
  schoolGrowing: '/school/growing',
  schoolOrganize: '/school/organize',
  cafePodcast: '/cafe/podcast',
  cafeSpace: '/cafe/space',
  marketPride: '/market/pride',
  marketFusion: '/market/fusion',
  legacy1: '/blank-1',
  legacy2: '/blank-2',
  legacy3: '/blank-3',
  legacy4: '/blank-4',
  legacy5: '/blank-5',
  legacy6: '/blank-6',
  legacy7: '/blank-7',
  legacy8: '/blank-8',
  legacy9: '/blank-9',
})
